COPY Airport(AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT) 
FROM 'C:\Users\Md Jahangir Alam\Desktop\Airport.csv' DELIMITER ',' CSV HEADER;


COPY States(STATE_NAME, STATE_ABR, STATE_FIPS, WAC)
FROM 'C:\Users\Md Jahangir Alam\Desktop\States.csv' DELIMITER ',' CSV HEADER; 


COPY Cities(CITY_NAME, STATE_ABR, CITY_MARKET_ID) 
FROM 'C:\Users\Md Jahangir Alam\Desktop\Cities.csv' DELIMITER ',' CSV HEADER;


COPY Carrier(AIRLINE_ID, UNIQUE_CARRIER_NAME, UNIQUE_CARRIER, UNIQUE_CARRIER_ENTITY)
FROM 'C:\Users\Md Jahangir Alam\Desktop\Carrier.csv' DELIMITER ',' CSV HEADER;


COPY Flight_Sum(AIRLINE_ID, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, RAMP_TO_RAMP, AIR_TIME, DEPARTURES_SCHEDULED, DEPARTURES_PERFORMED, 
PAYLOAD, SEATS, PASSENGERS, FREIGHT, MAIL, DISTANCE, YEAR, QUARTER, MONTH, DISTANCE_GROUP, CLASS)
FROM 'C:\Users\Md Jahangir Alam\Desktop\Flight_Sum.csv' DELIMITER ',' CSV HEADER;
 			
